<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"  name="scara_cpe">



		 
  <xacro:property name="Base_LENGTH" value="0.06" />
  <xacro:property name="Link1_LENGTH" value="0.08" />
  <xacro:property name="Link2_LENGTH" value="0.047" />
  <xacro:property name="Base_HEIGHT" value="0.03" />
  <xacro:property name="Link2_HEIGHT" value="-0.025" />
  <xacro:property name="PI" value="3.14159265359" />
  <xacro:property name="PI_half" value="1.57079632679" />



  <!-- LINK -->

  <link name="world"/>

  <link name="camera_link">
  <inertial>
    <mass value="0.001" />
    <origin xyz="0 0 0" />
    <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
             iyy="0.0001" iyz="0.0"
             izz="0.0001" />
    </inertial>
  </link>




  <link name="base_link">

    <visual>
      <origin xyz="0 0.034 0" rpy="-${PI_half} 0 -${PI_half}" />
      <geometry>
        <mesh filename="file://$(find scara_cpe_description)/urdf/scara_cpe-base_link.dae" scale="0.001 0.001 0.001"/>
      </geometry>
    </visual>

    <collision>
      <origin xyz="0 0.034 0" rpy="-${PI_half} 0 -${PI_half}" />
      <geometry>
        <mesh filename="file://$(find scara_cpe_description)/urdf/scara_cpe-base_link.dae" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision>    

    <inertial>
      <origin xyz="0 0.025 0" rpy="0 0 0" />
      <mass value="0.1"/>
      <inertia
        ixx="0.0001" ixy="1e-12" ixz="1e-12"
        iyy="0.0001" iyz="1e-12"
        izz="0.0001"/>
    </inertial>    

  </link>

  <link name="link1" >

    <visual>
      <origin xyz="0 -0.012 0" rpy="-${PI_half} 0 -${PI_half}" />
      <geometry>
        <mesh filename="file://$(find scara_cpe_description)/urdf/scara_cpe-link_1.dae" scale="0.001 0.001 0.001"/>
      </geometry>
    </visual>

    <collision>
      <origin xyz="0 ${Link1_LENGTH/2} 0" rpy="0 0 0" />
      <geometry>
        <box size="0.02 ${Link1_LENGTH/2} 0.05"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0.04 0" rpy="0 0 0" />
      <mass value="0.1"/>
      <inertia
        ixx="0.00003" ixy="1e-12" ixz="1e-12"
        iyy="0.00003" iyz="1e-12"
        izz="0.00003"/>
    </inertial>   

  </link>


  <link name="link2" >

    <visual>
	  <origin xyz="0.0133 -0.092 0" rpy="-${PI_half} 0 -1.42579632679" />  <!-- -1.42579632679  - pi/2 + 0.145 -->
      <geometry>
        <mesh filename="file://$(find scara_cpe_description)/urdf/scara_cpe-link_2.dae" scale="0.001 0.001 0.001"/>
      </geometry>
    </visual>

    <collision>
      <origin xyz="0 ${Link2_LENGTH/2} 0" rpy="0 0 0" />
      <geometry>
        <box size="0.032 ${Link2_LENGTH} 0.06"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0.02 0" rpy="0 0 0" />
      <mass value="0.1"/>
      <inertia
        ixx="0.0001" ixy="1e-12" ixz="1e-12"
        iyy="0.0001" iyz="1e-12"
        izz="0.0001"/>
    </inertial>  

  </link>


  <link name="end_link" >
  </link>



 <!-- JOINT -->

  <joint name="base_fixed" type="fixed">
    <parent link="world"/>
    <child link="base_link"/>
    <origin xyz="0 0 .035" rpy="0 0 0" />
  </joint>

  <joint name="camera_fixed" type="fixed">
    <parent link="world"/>
    <child link="camera_link"/>
    <origin xyz="0 -0.3 0.2" rpy="-${PI_half+0.3} 0 0" />
  </joint>

  <joint name="shoulder_1_joint" type="revolute">
    <parent link="base_link"/>
    <child link="link1"/>
    <origin xyz="0 0.048 0" rpy="0 0 0" />
	  <limit effort="0.1" velocity="1" lower="-${PI_half}" upper="${PI_half}" />
	  <axis xyz="0 0 1" />
  </joint>

  <joint name="shoulder_2_joint" type="revolute">
    <parent link="link1"/>
    <child link="link2"/>
    <origin xyz="0 0.08 0" rpy="0 0 0" /> 
	  <limit effort="0.1" velocity="1" lower="-2.8" upper="2.8" />
	  <axis xyz="0 0 -1" />
  </joint>


  <joint name="end_joint" type="fixed">
    <parent link="link2"/>
    <child link="end_link"/>
    <origin xyz="0 0.047 -0.025" rpy="0 0 0" />
  </joint>




    <!-- Import ros2_controller DYNAMIXEL elements -->
  <xacro:include filename="$(find scara_cpe_description)/urdf/scara_cpe.ros2_control.xacro" />

  <!-- Import ros2_controller elements -->
  <xacro:scara_cpe_ros2_control name="scara_cpe" />

    <!--<xacro:scara_cpe_ros2_emagnet_control name="scara_cpe" />-->



</robot>
